/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные настройки",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设置"},
    "Public-Key translations": {                     "en": "Public-Key translations",                         "de": "Public-Key-Übersetzungen",                        "ru": "Переводы с открытым ключом",                      "pt": "Traduções de chave pública",                      "nl": "Public-Key vertalingen",                          "fr": "Traductions de clé publique",                     "it": "Traduzioni a chiave pubblica",                    "es": "Traducciones de clave pública",                   "pl": "Tłumaczenia klucza publicznego",                  "zh-cn": "公钥翻译"},
    "Please add all your hosts running a WireGuard server instance which should be monitored.": {"en": "Please add all your hosts running a WireGuard server instance which should be", "de": "Bitte fügen Sie alle Ihre Hosts hinzu, auf denen eine WireGuard-Serverinstanz ausgeführt wird", "ru": "Пожалуйста, добавьте все ваши хосты, на которых запущен экземпляр сервера WireGuard, который должен быть", "pt": "Por favor, adicione todos os seus hosts executando uma instância do servidor WireGuard que deve ser", "nl": "Voeg a.u.b. al uw hosts toe die een WireGuard-serverexemplaar uitvoeren, wat zou moeten zijn:", "fr": "Veuillez ajouter tous vos hôtes exécutant une instance de serveur WireGuard qui devrait être", "it": "Aggiungi tutti i tuoi host che eseguono un'istanza del server WireGuard che dovrebbe essere", "es": "Agregue todos sus hosts que ejecutan una instancia de servidor WireGuard que debería ser", "pl": "Dodaj wszystkie hosty z instancją serwera WireGuard, która powinna być", "zh-cn": "请添加所有运行 WireGuard 服务器实例的主机，该实例应该是"},
    "Click here to add a new host": {                "en": "Click here to add a new host",                    "de": "Klicken Sie hier, um einen neuen Host hinzuzufügen", "ru": "Нажмите здесь, чтобы добавить новый хост",        "pt": "Clique aqui para adicionar um novo host",         "nl": "Klik hier om een ​​nieuwe host toe te voegen",    "fr": "Cliquez ici pour ajouter un nouvel hôte",         "it": "Fare clic qui per aggiungere un nuovo host",      "es": "Haga clic aquí para agregar un nuevo host",       "pl": "Kliknij tutaj, aby dodać nowego hosta",           "zh-cn": "单击此处添加新主机"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię",                                            "zh-cn": "姓名"},
    "Host address": {                                "en": "Host address (IP)",                               "de": "Hostadresse (IP)",                                "ru": "Адрес хоста",                                     "pt": "Endereço do host (IP)",                           "nl": "Host adres (IP)",                                 "fr": "Adresse de l'hôte (IP)",                          "it": "Indirizzo dell'host (IP)",                        "es": "Dirección del servidor (IP)",                     "pl": "Adres hosta (IP)",                                "zh-cn": "主机地址 (IP)"},
    "User": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Clave",                                           "pl": "Hasło",                                           "zh-cn": "密码"},
    "Poll interval": {                               "en": "Poll interval",                                   "de": "Abfrageintervall",                                "ru": "Интервал опроса",                                 "pt": "Intervalo de sondagem",                           "nl": "Poll-interval",                                   "fr": "Intervalle de sondage",                           "it": "Intervallo di sondaggio",                         "es": "Intervalo de encuesta",                           "pl": "Interwał sondowania",                             "zh-cn": "轮询间隔"},
    "Please add all public key to name translations here. This will make it more convenient for you to identify the peers in the object tree.": {"en": "Please add all public key to name translations here. This will make it more convenient for you to identify the peers in the object tree.", "de": "Bitte fügen Sie hier alle öffentlichen Schlüssel zu Namensübersetzungen hinzu. ", "ru": "Пожалуйста, добавьте сюда все открытые ключи для перевода имен. ", "pt": "Por favor, adicione todas as chaves públicas para traduções de nomes aqui. ", "nl": "Voeg hier alle openbare sleutels toe aan naamvertalingen. ", "fr": "Veuillez ajouter ici toutes les clés publiques pour nommer les traductions. ", "it": "Aggiungi qui tutte le chiavi pubbliche per le traduzioni dei nomi. ", "es": "Agregue todas las claves públicas para las traducciones de nombres aquí. ", "pl": "Dodaj tutaj wszystkie klucze publiczne do tłumaczeń nazw. ", "zh-cn": "请在此处添加所有公钥以命名翻译。"},
    "Click here to add a new translation": {         "en": "Click here to add a new translation",             "de": "Klicken Sie hier, um eine neue Übersetzung hinzuzufügen", "ru": "Нажмите здесь, чтобы добавить новый перевод",     "pt": "Clique aqui para adicionar uma nova tradução",    "nl": "Klik hier om een ​​nieuwe vertaling toe te voegen", "fr": "Cliquez ici pour ajouter une nouvelle traduction", "it": "Clicca qui per aggiungere una nuova traduzione",  "es": "Haga clic aquí para agregar una nueva traducción", "pl": "Kliknij tutaj, aby dodać nowe tłumaczenie",       "zh-cn": "单击此处添加新翻译"},
    "Public key": {                                  "en": "Public key",                                      "de": "Öffentlicher Schlüssel",                          "ru": "Открытый ключ",                                   "pt": "Chave pública",                                   "nl": "Publieke sleutel",                                "fr": "Clé publique",                                    "it": "Chiave pubblica",                                 "es": "Llave pública",                                   "pl": "Klucz publiczny",                                 "zh-cn": "公钥"},
};